version: "3.8"
services:
  web:
    build: .
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - media:/vol/web/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: photo_db
      POSTGRES_USER: photo_user
      POSTGRES_PASSWORD: photo_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  media: